---
- name: download {{ url }}
  get_url:
    url: "{{url}}"
    dest: "{{ download }}/{{ file }}"

- name: extract {{ download }}/{{ file }}
  become: yes
  become_method: sudo
  unarchive:
    owner: root
    group: root
    src: "{{ download }}/{{ file }}"
    dest: "{{ usr_local }}"
    copy: no
    creates: "{{ cassandra_home }}"

- name: set PATH=$PATH:{{ cassandra_home }}/bin
  become: yes
  become_method: sudo
  lineinfile:
    dest: "{{ etc_profiles }}/cassandra.sh"
    create: yes
    state: present
    regexp: '^PATH'
    line: 'PATH=$PATH:{{ cassandra_home }}/bin'

- stat:
    path: "{{ system_units }}/cassandra.service"
  register: cassandra_service

- name: stop cassandra
  become: yes
  become_method: sudo
  systemd:
    state: stopped
    name: cassandra
  when: cassandra_service.stat.exists
  tags:
    - stop

- name: copy server.properties {{ cassandra_home }}/conf/cassandra.yaml
  become: yes
  become_method: sudo
  template:
    src: templates/cassandra.yaml.j2
    dest: "{{ cassandra_home }}/conf/cassandra.yaml"

- name: create {{ cassandra_log_dir }}
  become: yes
  become_method: sudo
  file:
    path: "{{ cassandra_log_dir }}"
    state: directory

- name: install cassandra systemd unit file
  become: yes
  become_method: sudo
  template:
    src: templates/cassandra.service.j2
    dest: "{{ system_units }}/cassandra.service"

- name: start cassandra
  become: yes
  become_method: sudo
  systemd:
    enabled: yes
    state: started
    name: cassandra
    daemon_reload: yes
  tags:
    - start
